# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConcertNotifier.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConcertNotifier.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15\x43oncertNotifier.proto\"H\n\x13SubscriptionRequest\x12\x0c\n\x04\x43ity\x18\x01 \x03(\t\x12\x0c\n\x04\x42\x61nd\x18\x02 \x03(\t\x12\x15\n\x05Genre\x18\x03 \x03(\x0e\x32\x06.Genre\"*\n\x0c\x43oncertEvent\x12\x0c\n\x04\x43ity\x18\x01 \x01(\t\x12\x0c\n\x04\x42\x61nd\x18\x02 \x01(\t*\x85\x01\n\x05Genre\x12\x07\n\x03\x41LL\x10\x00\x12\x13\n\x0fSYMPHONIC_METAL\x10\x01\x12\x17\n\x13MELODIC_DEATH_METAL\x10\x02\x12\x0f\n\x0bPOWER_METAL\x10\x03\x12\x10\n\x0cTHRASH_METAL\x10\x04\x12\x12\n\x0e\x41\x43\x41PELLA_METAL\x10\x05\x12\x0e\n\nPROG_METAL\x10\x06\x32I\n\x0f\x43oncertNotifier\x12\x36\n\rTrackConcerts\x12\x14.SubscriptionRequest\x1a\r.ConcertEvent0\x01\x62\x06proto3'
)

_GENRE = _descriptor.EnumDescriptor(
  name='Genre',
  full_name='Genre',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYMPHONIC_METAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MELODIC_DEATH_METAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWER_METAL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THRASH_METAL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACAPELLA_METAL', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROG_METAL', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=144,
  serialized_end=277,
)
_sym_db.RegisterEnumDescriptor(_GENRE)

Genre = enum_type_wrapper.EnumTypeWrapper(_GENRE)
ALL = 0
SYMPHONIC_METAL = 1
MELODIC_DEATH_METAL = 2
POWER_METAL = 3
THRASH_METAL = 4
ACAPELLA_METAL = 5
PROG_METAL = 6



_SUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='SubscriptionRequest',
  full_name='SubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='City', full_name='SubscriptionRequest.City', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Band', full_name='SubscriptionRequest.Band', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Genre', full_name='SubscriptionRequest.Genre', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=97,
)


_CONCERTEVENT = _descriptor.Descriptor(
  name='ConcertEvent',
  full_name='ConcertEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='City', full_name='ConcertEvent.City', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Band', full_name='ConcertEvent.Band', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=141,
)

_SUBSCRIPTIONREQUEST.fields_by_name['Genre'].enum_type = _GENRE
DESCRIPTOR.message_types_by_name['SubscriptionRequest'] = _SUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['ConcertEvent'] = _CONCERTEVENT
DESCRIPTOR.enum_types_by_name['Genre'] = _GENRE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscriptionRequest = _reflection.GeneratedProtocolMessageType('SubscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTIONREQUEST,
  '__module__' : 'ConcertNotifier_pb2'
  # @@protoc_insertion_point(class_scope:SubscriptionRequest)
  })
_sym_db.RegisterMessage(SubscriptionRequest)

ConcertEvent = _reflection.GeneratedProtocolMessageType('ConcertEvent', (_message.Message,), {
  'DESCRIPTOR' : _CONCERTEVENT,
  '__module__' : 'ConcertNotifier_pb2'
  # @@protoc_insertion_point(class_scope:ConcertEvent)
  })
_sym_db.RegisterMessage(ConcertEvent)



_CONCERTNOTIFIER = _descriptor.ServiceDescriptor(
  name='ConcertNotifier',
  full_name='ConcertNotifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=279,
  serialized_end=352,
  methods=[
  _descriptor.MethodDescriptor(
    name='TrackConcerts',
    full_name='ConcertNotifier.TrackConcerts',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIPTIONREQUEST,
    output_type=_CONCERTEVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONCERTNOTIFIER)

DESCRIPTOR.services_by_name['ConcertNotifier'] = _CONCERTNOTIFIER

# @@protoc_insertion_point(module_scope)
